# Generated by Django 4.1 on 2024-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodhub_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=64, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=64, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=64, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=16, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=256, null=True)),
                ('review_categories', models.CharField(blank=True, max_length=256, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=256, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=32, null=True)),
                ('collection_time', models.CharField(blank=True, max_length=32, null=True)),
                ('town', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook', models.CharField(blank=True, max_length=128, null=True)),
                ('twitter', models.CharField(blank=True, max_length=128, null=True)),
                ('android_link', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('seo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Foodhub',
            },
        ),
    ]
