# Generated by Django 5.1 on 2024-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('uniqueName', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=16, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('lng', models.CharField(blank=True, max_length=32, null=True)),
                ('lat', models.CharField(blank=True, max_length=32, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('starRating', models.CharField(blank=True, max_length=16, null=True)),
                ('isNew', models.CharField(blank=True, max_length=16, null=True)),
                ('openingTimeLocal', models.CharField(blank=True, max_length=64, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=256, null=True)),
                ('deliveryFees', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'Justeat',
            },
        ),
    ]
