# Generated by Django 4.1 on 2024-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhouse',
            name='map_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
