# Generated by Django 4.1 on 2024-09-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubereats',
            old_name='lat',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='ubereats',
            old_name='lng',
            new_name='Longitude',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='cuisines',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='deliveryFees',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='isNew',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='openingTimeLocal',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='starRating',
        ),
        migrations.AlterModelTable(
            name='foodhouse',
            table='Foodhouse',
        ),
    ]
