# Generated by Django 4.1 on 2024-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_foodhouse_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhouse',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodhouse',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
