# Generated by Django 5.1 on 2024-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_justeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('uniqueName', models.CharField(blank=True, max_length=32, null=True)),
                ('url_map', models.CharField(blank=True, max_length=64, null=True)),
                ('map_preview_url', models.CharField(blank=True, max_length=64, null=True)),
                ('about_text', models.CharField(blank=True, max_length=255, null=True)),
                ('email_business', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=64, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=64, null=True)),
                ('google_play_link', models.CharField(blank=True, max_length=64, null=True)),
                ('app_store_link', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('main_text', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('openingHoursReadable', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=16, null=True)),
                ('postcode', models.CharField(blank=True, max_length=16, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_count', models.CharField(blank=True, max_length=16, null=True)),
                ('rating_average', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'WTF',
            },
        ),
    ]
